minio:
    upload-endpoint: ${MINIO_UPLOAD_ENDPOINT:${MINIO_ENDPOINT:http://localhost:9000}}
    public-endpoint: ${MINIO_PUBLIC_ENDPOINT:${MINIO_UPLOAD_ENDPOINT:${MINIO_ENDPOINT:http://localhost:9000}}}
    access-key: ${MINIO_ACCESS_KEY:wwan13}
    secret-key: ${MINIO_SECRET_KEY:xodhksalsdkdldh}
