server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    include:
      - jpa
      - redis
      - minio
      - messaging
      - jwt
      - oauth
      - minio
      - object-storage
