server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    include:
      - jpa
      - redis
      - minio
      - messaging
      - jwt
      - oauth

upload:
  image:
    bucket: ${UPLOAD_IMAGE_BUCKET:baezzal-images}
    prefix: ${UPLOAD_IMAGE_PREFIX:images}
    presigned-expiry-seconds: ${UPLOAD_IMAGE_PRESIGNED_EXPIRY_SECONDS:600}
