ALTER TABLE team
    ADD COLUMN code VARCHAR(50) NULL AFTER team_id;

UPDATE team
SET code = CASE team_id
    WHEN 1 THEN 'LG'
    WHEN 2 THEN 'HANWHA'
    WHEN 3 THEN 'SSG'
    WHEN 4 THEN 'SAMSUNG'
    WHEN 5 THEN 'NC'
    WHEN 6 THEN 'KT'
    WHEN 7 THEN 'LOTTE'
    WHEN 8 THEN 'KIA'
    WHEN 9 THEN 'DOOSAN'
    WHEN 10 THEN 'KIWOOM'
END;

ALTER TABLE team
    MODIFY COLUMN code VARCHAR(50) NOT NULL;

ALTER TABLE team
    ADD CONSTRAINT uk_team_code UNIQUE (code);
